model_version: "1.5"
model_name: dreamlike-art/dreamlike-photoreal-2.0
negative_prompt: lowres, bad anatomy, bad hands, cropped, worst quality
sample_prompt: yes
n_images: 4
n_rounds: 3
num_prompts: 1000
guidance_scale: 6
denoising_steps: 20
feedback:
  start: 0.0
  end: 1.0
  min_weight: 0.1
  max_weight: 0.8
  neg_scale: 0.5
global_seed: 0
image_seed: null
liked_images: []
disliked_images: []
output_path: outputs/preference_model_feedback

# For loading the Human Preference Score LoRA weights, set null to not use them
lora_weights: null  # fabric/resources/hps_lora/adapted_model.bin